### ISSUE TITLE
使用http协议发布消息问题

### ISSUE THREAD

**Issue by supiyun** [fanux/lhttp#10]
**使用http协议发布消息问题，使用和文档中的方式类进行调用，调用失败**
http.POST("http://127.0.0.1:8581/publish", "text/plain",
    "LHTTP/1.0 chat\r\npublish:channel_test\r\n\r\nhello channel_test guys!")
直接调用不通。
**换成**
http.POST("http://127.0.0.1:8581/chat", "text/plain",
    "LHTTP/1.0 chat\r\npublish:channel_test\r\n\r\nhello channel_test guys!")
返回：bad method

**Comment by fanux** [comment]
目测你可能发送的是原始字符串，\r\n变成原始字符串了。你是用js发的还是go？或者是一些测试工具？
```
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"
)

func main() {
	resp, err := http.Post("http://127.0.0.1:8581/publish", "text/plain", strings.NewReader("LHTTP/1.0 chat\r\npublish:channel_test\r\n\r\nhello channel_test guys!"))
	if err != nil {
		fmt.Println(err)
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
	}
	fmt.Println(string(body))
}
```
这个测试用例是没有问题的。服务端会收到：
```
2017/09/27 09:12:45 http publish body: LHTTP/1.0 chat
publish:channel_test

hello channel_test guys!
```
而不是：
```
2017/09/27 08:59:41 http publish body: LHTTP/1.0 chat\r\npublish:channel_test\r\n\r\nhello channel_test guys!
```
我用js试了一下，也没有问题：
```
 $.post("http://127.0.0.1:8581/publish",
"LHTTP/1.0 chat\r\npublish:channel_test\r\n\r\nhello channel_test guys!",
  function(data,status){
    alert("Data: " + data + "\nStatus: " + status);
  });
```

**Comment by supiyun** [comment]
感谢回复！
我启动的是：websocketServer 下面的test.go 里面没有publish的地址。是不是还要起另外一个或者要加其他的那段代码。谢谢

**Comment by fanux** [comment]
不需要加，publish在mq里定义的，是框架的功能。 test.go只是个事例。

**Comment by supiyun** [comment]
找到问题了，我的是开发用的是mac，调用http用的是postman。我这边传输过去的回车是：\n
