### ISSUE TITLE
websocketClient里面的test.go有误

### ISSUE THREAD

**Issue by yinjiaoyuan** [fanux/lhttp#11]
这个文件里面的suubpub应该为subpub，有好几个地方出现，还有cam_123应该为camera_123吧。

**Comment by fanux** [comment]
貌似是的，不过这只是个测试文件。 要你改改merge进来？

**Comment by yinjiaoyuan** [comment]
好的，我稍后有时间整理一下merge进来。

**Comment by yinjiaoyuan** [comment]
我git clone https://github.com/fanux/lhttp.git后修改文件，然后git add文件，接着git commit和git push后输入我在github上到用户名和密码会提示没有权限。

**Comment by fanux** [comment]
需要fork到自己的仓库，然后pullrequest请求合并，我会审核通过。

**Comment by yinjiaoyuan** [comment]
已经pull request，请审核通过，谢谢。
