### ISSUE TITLE
关于unnsubscribe不了的问题

### ISSUE THREAD

**Issue by yinjiaoyuan** [fanux/lhttp#12]
我使用websocketServer里面的test .go做服务器，然后启动websocketClient里面的test.go做客户端进行测试，我nsubscribe了camera_123后并且publish一个消息后camera_123可以接收到，但是我unsubscribe了camera_123后还是可以接收到消息，这样好像不对吧。谢谢。

**Comment by gamegrd** [comment]
这个可以关了，现在能正确　unsubscribe    ：　[https://github.com/fanux/lhttp/commit/8ec8c4ad93de5d7fb0580b34e457f8bb9f16edbe](url)
