### ISSUE TITLE
当用户  close 的时候,是否需要先 unnsubscribe 释放资源?

### ISSUE THREAD

**Issue by gamegrd** [fanux/lhttp#14]
当用户  close 的时候,是否需要先 unnsubscribe 释放资源?

**Comment by fanux** [comment]
最好先释放

**Comment by gamegrd** [comment]
也就是说 服务器端并没有管理用户 订阅了哪些频道,  需要自己管理,如果 用户意外断线,也需要自己加入必跳功能方能正确处理?

**Comment by fanux** [comment]
对  lhttp是个轻量级框架，本身不存储这些信息。

**Comment by gamegrd** [comment]
感谢回复,发解了
