### ISSUE TITLE
wsHandler.go里面的buildMessage没有做防错

### ISSUE THREAD

**Issue by WangPengJu** [fanux/lhttp#19]
如果消息是:
"LHTTP/1.0 chat\r\n
\r\n
nihao"
那么必然会在range里面报错 数组下标越界 这边应该做个处理

//parse websocket body
func buildMessage(data string) *WsMessage {
	//TODO optimise ,to use builder pattern
	s := data
	message := &WsMessage{message: data}
	message.headers = make(map[string]string, headerMax)
	//parse message

	//parse start line
	i := strings.Index(s, CRLF)
	message.command = s[protocolLength+1 : i]

	//parse hearders
	k := 0
	headers := s[i+2:]
	var key string
	var value string
	//traverse once
	for j, ch := range headers {
		if ch == ':' && key == "" {
			key = headers[k:j]
			k = j + 1
		} else if headers[j:j+2]（这边） == CRLF {
			value = headers[k:j]
			k = j + 2

			message.headers[key] = value
			// log.Print("parse head key:", key, " value:", value)
			key = ""
		}
		if headers[k:k+2] （这边）== CRLF {
			k += 2
			break
		}
	}

	//set body
	message.body = headers[k:]

	return message
}

**Comment by fanux** [comment]
ok  你来提交pull request

**Comment by WangPengJu** [comment]
好的

**Comment by WangPengJu** [comment]
已经pull request了。  能否加一下我的QQ： 19352226。 我这边还有一些东西要请教你一下。
