### ISSUE TITLE
多个lhttp server的问题

### ISSUE THREAD

**Issue by yinjiaoyuan** [fanux/lhttp#24]
为了支撑大量用户（例如20万用户）的websocket连接，我部署多个lhttp server，例如有lhttp server1和lhttp server2，如果client1通过websocket连接到lhttp server1，client2通过websocket连接到lhttp server2，client2 subscribe了client1的message，那client1 publish到lhttp server1的message如何让client2接收到？谢谢。

**Comment by fanux** [comment]
Lhttp后端使用[gnatsd](https://github.com/nats-io/gnatsd)消息队列做消息中心, 每个lhttp server的后端地址都配置成gnatsd地址即可https://github.com/fanux/lhttp/blob/master/mq.go#L70
