### ISSUE TITLE
run error!

### ISSUE THREAD

**Issue by hongxiangbin** [fanux/lhttp#4]
hello,Could you describe this command in detail?

“We need run gnatsd first:
cd bin
./gnatsd &
./lhttpd 
......”

gnatsd & lhttpd  is not a command

**Comment by fanux** [comment]
There are two commands, first run `./gnatsd &`  will run a gnatsd daemon, then run `./lhttpd`.
We use gnatsd as a message queue, then clients can use subscribe/publish headers.  If you run bin on others platform not linux, you need to rebuild source code, `go get github.com/nats-io/gnatsd`, `cd websocketServer` `go build -o lhttpd`.  Using [docker](https://github.com/fanux/lhttp#ship-on-docker) also a good choice.

**Comment by hongxiangbin** [comment]
I konw, beacuse  I's running in Windows before
But,it still can't run!

**Comment by fanux** [comment]
Did you rebuild the project?
```
go get github.com/nats-io/gnatsd
go get github.com/fanux/lhttp
cd  websocketServer
go build -o lhttpd
gnatsd &
./lhttpd
```

**Comment by hongxiangbin** [comment]
Thanks, it has run successfully on Linux
